#include "base/base_arena.c"
#include "base/base.c"
#include "common/logger.c"
#include "journal/journald.c"
#include "libnet/net.c"
#include "libres/resources.cc"
#include "dbus/dbushandler.cc"
#include "auth/auth.cc"
#include "grpc/generated/resources/v3/deviceresources.pb.cc"
#include "grpc/generated/resources/v3/deviceresources.grpc.pb.cc"
#include "grpc/handlers/resource_handler.cc"
#include "grpc/server/server.cc"
#include "agent/core.cc"

/*
#include "libvm/qc.c"
include "libpkg/pkg.c"
#include "libpkg/distro/arch_pac.cc"
#include "libpkg/distro/debian_apt.cc"
#include "libpkg/distro/fedora_dnf.cc"
*/
